---
title: "Article volume"
output: github_document
---

```{r, knitr_setup, echo=FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = TRUE,
  fig.width = 6,
  fig.asp = 0.618,
  out.width = "70%",
  fig.align = "center",
  dpi = 300
)
options(scipen = 999, digits = 4)
knitr::knit_hooks$set(
  inline = function(x) {
    if (is.numeric(x)) {
      return(prettyNum(x, big.mark = ","))
    } else{
      return(x)
    }
  }
)
```

```{r r_setup}
library(bigrquery)
library(tidyverse)
library(patchwork)
#' Connect to DB 
#' 
#' BigQuery HOAD (Crossref, OpenAlex and open friends)
bq_con <- dbConnect(
  bigrquery::bigquery(),
  project = "subugoe-collaborative",
  billing = "subugoe-collaborative"
)
```

```{r data_setup}
# Web of Science
wos_by_year <- readr::read_csv(here::here("data", "wos_by_year.csv"))
wos_ta_by_year <- readr::read_csv(here::here("data", "wos_ta_by_year.csv"))

wos_df <- inner_join(wos_by_year, wos_ta_by_year, by = c("earliest_year", "pub_type" = "pubtype"))

# Scopus
scp_by_year <- readr::read_csv(here::here("data", "scp_by_year.csv"))
scp_ta_by_year <- readr::read_csv(here::here("data", "scp_ta_by_year.csv"))

scp_df <- inner_join(scp_by_year, scp_ta_by_year, by = c("earliest_year" = "first_pubyear", "pub_type" = "pubtype"))

#scp_jn_by_year <- readr::read_csv(here::here("data", sc))
```

```{r ta_oa_by_year}
# core
wos_oa_by_year <- wos_df |> 
  filter(pub_type == "core") |> 
  select(earliest_year, n_articles, n_oa_articles, ta_oa_articles,
         ta_oa_first_author_articles, ta_oa_corresponding_author_articles) |> 
  pivot_longer(c(ta_oa_articles, ta_oa_first_author_articles, ta_oa_corresponding_author_articles)) |> 
  mutate(src = "Web of Science")


scp_oa_by_year <- scp_df |> 
  filter(pub_type == "core") |> 
  select(earliest_year, n_articles, n_oa_articles, ta_oa_articles,
         ta_oa_first_author_articles, ta_oa_corresponding_author_articles) |> 
  pivot_longer(c(ta_oa_articles, ta_oa_first_author_articles, ta_oa_corresponding_author_articles)) |> 
  mutate(src = "Scopus")

wos_oa_by_year_plot <- ggplot() +
  geom_bar(
    data = distinct(wos_oa_by_year, earliest_year, n_oa_articles, n_articles),
    aes(
      x = earliest_year,
      y = n_oa_articles,
      fill = "All"
    ),
    stat = "identity",
    color = "#000000"
  ) +
  geom_bar(
    data = wos_oa_by_year,
    aes(
      x = earliest_year,
      y = value,
      fill = "TA OA"
    ),
    stat = "identity",
    color = "#000000"
  ) +
  facet_grid(src ~ name) +
  scale_fill_manual(
    values = c("#b3b3b3a0", "#56B4E9"),
    name = "",
    guide = guide_legend(reverse = TRUE)
  ) +
  # scale_y_continuous(
  #   expand = expansion(mult = c(0, 0.05)),
  #   labels = scales::percent_format(),
  #   limits = c(0, .20),
  #   breaks = c(0, .05, .1, .15)
  # ) +
  theme_minimal() +
  labs(y = "Hybrid OA Uptake", x = NULL) +
  theme(
    legend.position = "top",
    legend.justification = "left",
    axis.text.x = element_blank()
  )


scp_oa_by_year_plot <- ggplot() +
  geom_bar(
    data = distinct(scp_oa_by_year, earliest_year, n_oa_articles, n_articles),
    aes(
      x = earliest_year,
      y = n_oa_articles,
      fill = "All"
    ),
    stat = "identity",
    color = "#000000"
  ) +
  geom_bar(
    data = scp_oa_by_year,
    aes(
      x = earliest_year,
      y = value,
      fill = "TA OA"
    ),
    stat = "identity",
    color = "#000000"
  ) +
  facet_grid(src ~ name) +
  scale_fill_manual(
    values = c("#b3b3b3a0", "#56B4E9"),
    name = "",
    guide = guide_legend(reverse = TRUE)
  ) +
  # scale_y_continuous(
  #   expand = expansion(mult = c(0, 0.05)),
  #   labels = scales::percent_format(),
  #   limits = c(0, .20),
  #   breaks = c(0, .05, .1, .15, 0.2)
 # ) +
  theme_minimal() +
  labs(y = "Hybrid OA Uptake", x = NULL) +
  theme(
    legend.position = "top",
    legend.justification = "left",
    axis.text.x = element_blank()
  )

wos_oa_by_year_plot / scp_oa_by_year_plot + plot_layout(axes = "collect", axis_titles = "collect")
```

## Check Overlap

```{r}
# Overlap data
jn_overlap <- readr::read_csv(here::here("data", "jn_upset_articles.csv"))

# Get TA DOIs and upset
hoad_ta_oa_dois <- readr::read_csv(here::here("data-raw", "ta_oa_inst.csv")) |>
  filter(cr_year %in% 2018:2023, ta_active == TRUE, !is.na(cc)) |> 
  distinct(doi) |>
  mutate(src = "hoad")

wos_scp_ta_oa_dois <- DBI::dbGetQuery(bq_con, "SELECT DISTINCT doi, issn_l, author_seq_nr, corresponding, 'Scopus' AS src
FROM `hoa-article.hoa_comparision.scp_jct_match` 
WHERE ta_flag = TRUE AND core = TRUE AND oa_status LIKE '%hybrid%' AND first_pubyear BETWEEN 2018 AND 2023
UNION ALL
SELECT DISTINCT doi, issn_l, author_seq_nr, corresponding, 'Web of Science' AS src
FROM `hoa-article.hoa_comparision.wos_jct_match` 
WHERE ta_flag = TRUE AND core = TRUE AND oa_status LIKE '%hybrid%' AND earliest_year BETWEEN 2018 AND 2023")

my_df <- wos_scp_ta_oa_dois |>
  filter(corresponding == TRUE) |>
  bind_rows(hoad_ta_oa_dois) |>
  distinct(doi, src, issn_l)

# Create binary columns for each source
data_wide <- my_df |>
  mutate(value = 1) |>
  # Split sources if they contain multiple values
#  separate_rows(src, sep = " and ") %>%
  # Create wide format with binary indicators
  pivot_wider(
    id_cols = c(doi, issn_l),
    names_from = src,
    values_from = value,
    values_fill = 0
  )

# Create the UpSet plot
upset_plot <- upset(
  data_wide,
  intersect = colnames(data_wide)[-1],  # Exclude the DOI column
  name = "Source Intersections",
  width_ratio = 0.1,
  themes = upset_modify_themes(
    list(
      "intersections_matrix" = theme(
        text = element_text(size = 10),
        plot.margin = margin(1, 1, 1, 1, "cm")
      ),
      "Intersection size" = theme(
        axis.text.y = element_text(size = 10),
        axis.title.y = element_text(size = 12)
      ),
      "Overall set size" = theme(
        axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
        axis.title.x = element_text(size = 12)
      )
    )
  ),
  set_sizes = (
    upset_set_size() + 
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  ),
  matrix = (
    intersection_matrix(
      geom = geom_point(size = 3)
    )
  ),
  base_annotations = list(
    "Intersection size" = intersection_size(
      mapping = aes(fill = "black")
    )
  )
)
```

```{r}
tt <- wos_scp_ta_oa_dois |>
  mutate(cat = ifelse(author_seq_nr == 1, paste0("first_", src), paste0("corresponding_", src))) |> bind_rows(hoad_ta_oa_dois) |>
  distinct(doi, cat) |>
  mutate(cat = ifelse(is.na(cat), "first_hoad", cat))

tt_wide <- tt |>
 # select(-issn_l) |>
  mutate(value = 1) |>
  pivot_wider(
    id_cols = c(doi),
    names_from = cat,
    values_from = value,
    values_fill = 0
  )



upset_plot <- upset(
  tt_wide,
  intersect = colnames(tt_wide)[-1],
  name = "Source Intersections",
  group_by = "sets")


```

