---
title: "eda"
output: github_document
---

```{r, knitr_setup, echo=FALSE}
knitr::opts_chunk$set(
  comment = "#>",
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  echo = TRUE,
  fig.width = 6,
  fig.asp = 0.618,
  out.width = "70%",
  fig.align = "center",
  dpi = 300
)
options(scipen = 999, digits = 4)
knitr::knit_hooks$set(
  inline = function(x) {
    if (is.numeric(x)) {
      return(prettyNum(x, big.mark = ","))
    } else{
      return(x)
    }
  }
)
```

```{r r_setup}
library(bigrquery)
library(tidyverse)
#' Connect to DB 
#' 
#' BigQuery HOAD (Crossref, OpenAlex and open friends)
bq_con <- dbConnect(
  bigrquery::bigquery(),
  project = "subugoe-collaborative",
  billing = "subugoe-collaborative"
)
```

## Web of Science

### Open access

```{sql add_oa_info, connection = bq_con, output.var = "wos_oa"}
WITH oa_raw AS (SELECT DISTINCT item_id, doi, issn_l, CASE WHEN online_year IS NULL THEN pubyear ELSE online_year END AS earliest_year, is_oa
FROM (
SELECT
  wos.item_id, 
  wos.doi, 
  wos.issn_l,
  wos.pubyear,
  CAST(REGEXP_EXTRACT(wos_pubdate_online, r'^[0-9]{4}') AS NUMERIC) AS online_year,
  CASE
    WHEN cc IS NOT NULL AND vor = 1 THEN TRUE
  ELSE
  FALSE
END
  AS is_oa
FROM
  `hoa-article.hoa_comparision.wos_matching_20240410` AS wos
LEFT JOIN
  `subugoe-collaborative.hoaddata.cc_md` AS cc
ON
  wos.doi = cc.doi ) )
SELECT COUNT(DISTINCT item_id) as wos_articles, issn_l, earliest_year, is_oa
FROM oa_raw
GROUP BY issn_l, earliest_year, is_oa
ORDER BY issn_l, earliest_year
```

By year

```{r}
wos_all <- wos_oa |>
  group_by(earliest_year) |>
  summarise(articles = sum(wos_articles))

wos_oa |>
  filter(is_oa == TRUE) |>
  group_by(earliest_year) |>
  summarise(oa = sum(wos_articles)) |>
  right_join(wos_all) |>
  mutate(prop = oa / articles)
```

## Compare to HOAD

```{r}
wos_jn_all <- wos_oa |>
  group_by(earliest_year) |>
  summarise(journals = n_distinct(issn_l),
            articles = sum(wos_articles))

wos_oa_per_year <-  wos_oa |>
  filter(is_oa == TRUE) |>
  group_by(earliest_year) |>
  summarise(oa_journals = n_distinct(issn_l),
            oa_articles = sum(wos_articles))

wos_per_year <- inner_join(wos_jn_all, wos_oa_per_year)

cr_all_per_year <- hoaddata::jn_ind |> 
  distinct(issn_l, cr_year, jn_all) |>
  group_by(cr_year) |>
  summarise(cr_journals = n_distinct(issn_l),
            cr_articles = sum(jn_all)) 

cr_oa <- hoaddata::jn_ind |>
  filter(!is.na(cc)) |> group_by(cr_year) |>
  summarise(cr_oa = sum(cc_total))

cr_per_year <- inner_join(cr_all_per_year, cr_oa) |>
  mutate(cr_year = as.numeric(as.character(cr_year)))

my_df_year <- inner_join(cr_per_year, wos_per_year, by = c("cr_year" = "earliest_year")) |>
  mutate(cr_oa_prop = cr_oa / cr_articles,
         wos_oa_prop = oa_articles / articles)

### journal level

wos_jn_all <- wos_oa |>
  group_by(earliest_year, issn_l) |>
  summarise(articles = sum(wos_articles))

wos_oa_per_year <-  wos_oa |>
  filter(is_oa == TRUE) |>
  group_by(earliest_year, issn_l) |>
  summarise(oa_articles = sum(wos_articles))

wos_per_year <- inner_join(wos_jn_all, wos_oa_per_year)

cr_all_per_year <- hoaddata::jn_ind |> 
  distinct(issn_l, cr_year, jn_all) |>
  group_by(cr_year, issn_l) |>
  summarise(cr_articles = sum(jn_all)) 

cr_oa <- hoaddata::jn_ind |>
  filter(!is.na(cc)) |> group_by(cr_year, issn_l) |>
  summarise(cr_oa = sum(cc_total))

cr_per_year <- inner_join(cr_all_per_year, cr_oa) |>
  mutate(cr_year = as.numeric(as.character(cr_year)))

my_df <- inner_join(cr_per_year, wos_per_year, by = c("cr_year" = "earliest_year", "issn_l")) |>
  mutate(cr_oa_prop = cr_oa / cr_articles,
         wos_oa_prop = oa_articles / articles)
```

### wos_jct_items_approach

use items from kb, distinguishing between doc types and provides oa information

```{r}
wos_jct_items_raw <- readr::read_csv(here::here("data-raw/", "wos_jct_items_df.csv")) 
wos_jct_items <- wos_jct_items_raw|>
  mutate(core_pub = ifelse(grepl("Article|Review", item_type), 1, 0),
         hybrid_oa = ifelse(grepl("hybrid", oa_status), 1, 0),
         cr_oa = ifelse(tolower(doi) %in% hoaddata::cc_articles$doi, 1, 0),
         online_year = lubridate::year(wos_pubdate_online)) |>
  mutate(earlies_year = ifelse(!is.na(online_year), online_year, pubyear)) |>
  distinct()
```


## stats

```{r}
core_hybrid_oa <- wos_jct_items |>
  filter(core_pub == 1) |>
  group_by(earlies_year) |>
  summarise(core_hybrid_oa = sum(hybrid_oa),
            core_cr_oa = sum(cr_oa))

wos_24_stat <- wos_jct_items |>
  group_by(earlies_year) |>
  summarise(all = n_distinct(item_id),
            core = sum(core_pub),
            hybrid_oa = sum(hybrid_oa),
            cr_oa = sum(cr_oa)) |>
  inner_join(core_hybrid_oa) |>
  mutate(oa_prop = hybrid_oa / all,
         core_oa_prop = core_hybrid_oa / core,
         cr_prop = cr_oa / all,
         core_cr_prop = core_cr_oa / core) 

#write_csv(wos_oct_23_stat, here::here("data", "wos_oct_23_stat.csv"))
```

## by journal

```{r}

## Wos data

jn_core_hybrid_oa <- wos_jct_items |>
  filter(core_pub == 1) |>
  group_by(earlies_year, issn_l) |>
  summarise(core_hybrid_oa = sum(hybrid_oa),
            core_cr_oa = sum(cr_oa))

jn_wos_24_stat <- wos_jct_items |>
  group_by(earlies_year, issn_l) |>
  summarise(all = n_distinct(item_id),
            core = sum(core_pub),
            hybrid_oa = sum(hybrid_oa),
            cr_oa = sum(cr_oa)) |>
  inner_join(jn_core_hybrid_oa) |>
  mutate(oa_prop = hybrid_oa / all,
         core_oa_prop = core_hybrid_oa / core,
         cr_prop = cr_oa / all,
         core_cr_prop = core_cr_oa / core) 

## hoaddata

cr_all_per_year <- hoaddata::jn_ind |> 
  distinct(issn_l, cr_year, jn_all) |>
  group_by(cr_year, issn_l) |>
  summarise(hoad_articles = sum(jn_all)) 

cr_oa <- hoaddata::jn_ind |>
  filter(!is.na(cc)) |> 
  group_by(cr_year, issn_l) |>
  summarise(hoad_oa = sum(cc_total))

cr_per_year <- left_join(cr_all_per_year, cr_oa) |>
  mutate(cr_year = as.numeric(as.character(cr_year)))

jn_wos_stats <- left_join(cr_per_year, jn_wos_24_stat, by = c("cr_year" = "earlies_year" , "issn_l"))

## add esac portfolios

### in the anayltics, we need to decide whether we anaylse the intersection or the scenario all journals

publisher_intersection_df <- hoaddata::jct_hybrid_jns |>
  distinct(issn_l, esac_publisher) |>
  inner_join(jn_wos_stats, by = "issn_l") |>
  filter(cr_year %in% 2018:2023) |>
  # only intersection
  filter(!is.na(all)) |>
  group_by(esac_publisher) |>
  summarise(all = sum(all),
            core = sum(core),
            hybrid_oa = sum(hybrid_oa),
            core_hybrid_oa = sum(core_hybrid_oa),
            cr_oa = sum(cr_oa),
            core_cr_oa = sum(core_cr_oa),
            hoad_articles = sum(hoad_articles, na.rm = TRUE),
            hoad_oa = sum(hoad_oa, na.rm = TRUE)) 

publisher_intersection_by_year_df <- hoaddata::jct_hybrid_jns |>
  distinct(issn_l, esac_publisher) |>
  inner_join(jn_wos_stats, by = "issn_l") |>
  filter(cr_year %in% 2018:2023) |>
  # only intersection
  filter(!is.na(all)) |>
  group_by(esac_publisher, cr_year) |>
  summarise(all = sum(all),
            core = sum(core),
            hybrid_oa = sum(hybrid_oa),
            core_hybrid_oa = sum(core_hybrid_oa),
            cr_oa = sum(cr_oa),
            core_cr_oa = sum(core_cr_oa),
            hoad_articles = sum(hoad_articles, na.rm = TRUE),
            hoad_oa = sum(hoad_oa, na.rm = TRUE))


p <- ggplot(publisher_intersection_by_year_df, aes(core_hybrid_oa, core_cr_oa, text = esac_publisher)) +
  geom_point(alpha = 0.4) +
  #scale_x_log10(limits = c(1,100000)) +
  #scale_y_log10(limits = c(1,100000)) +
  coord_equal() +
  geom_abline(slope = 1, intercept = 0)  +
  # geom_smooth(method = "lm") +
  facet_wrap(~ cr_year) 
plotly::ggplotly(p)
```

### Exploration

```{r}
ggplot(jn_wos_stats, aes(hoad_oa / hoad_articles, core_cr_prop)) +
  geom_point(alpha = 0.05) +
  scale_x_log10(limits = c(0.001,1)) +
  scale_y_log10(limits = c(0.001,1)) +
  coord_equal() +
  geom_abline(slope = 1, intercept = 0)  +
  facet_wrap(~ cr_year)
```